name: ShiftVision
favicon: null
layout_spectrum: 0.51355
typography_spectrum: 0.83243
title: Test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.875
  lightness: 0.6875
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
